---
- name: jenkins deployment
  become: yes
  task: 
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /usr/share/tomcat/webapps/jenkins.war

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
  
  - name: install tomcat
    yum:
      name: tomcat 
      state: present

  - name: tomcat enable and started
    service:
      name: tomcat
      state: started 
      enabled: yes
